Fb b3
alexis-allemann/PRO-B01 pull request #37
Opened 2021-03-27 10:44 UTC by alexis-allemann

Fin de la mise en place de la navigation
Ferme #16

2021-03-27 15:18 UTC, alex-mottier submitted a review, later dismissed

2021-03-29 11:45 UTC, AloisChristen commented on Client/src/screens/Student/Home/styles.ts
> + * @file    stlyes.ts
typo

2021-03-29 11:46 UTC, AloisChristen commented on Client/src/screens/Student/Profile/styles.ts
> + * @file    stlyes.ts
typo

2021-03-29 11:46 UTC, AloisChristen commented on Client/src/screens/Student/Search/styles.ts
> + * @file    stlyes.ts
typo

2021-03-29 11:47 UTC, AloisChristen requested changes
3 typos à corriger, le reste est bon

2021-03-29 11:52 UTC, AloisChristen approved these changes

2021-03-29 11:53 UTC, merged